### ISSUE TITLE
Unknown cursor error

### ISSUE THREAD

**Issue by j-rewerts** [coe-google-apps-support/DriveTransfer#43]
MongoError: Cursor not found, cursor id: 17114928981
    at Function.MongoError.create (C:\Users\jarrew\Documents\Projects\DriveTrans
fer\task-server\node_modules\mongodb-core\lib\error.js:31:11)
    at C:\Users\jarrew\Documents\Projects\DriveTransfer\task-server\node_modules
\mongodb-core\lib\connection\pool.js:497:72
    at authenticateStragglers (C:\Users\jarrew\Documents\Projects\DriveTransfer\
task-server\node_modules\mongodb-core\lib\connection\pool.js:443:16)
    at Connection.messageHandler (C:\Users\jarrew\Documents\Projects\DriveTransf
er\task-server\node_modules\mongodb-core\lib\connection\pool.js:477:5)
    at Socket.<anonymous> (C:\Users\jarrew\Documents\Projects\DriveTransfer\task
-server\node_modules\mongodb-core\lib\connection\connection.js:331:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)

**Comment by j-rewerts** [comment]
Haven't been able to identify the cause. [There](https://github.com/meteor/meteor/issues/7763) [are](https://github.com/Automattic/mongoose/issues/3927) [multiple](https://jira.mongodb.org/browse/NODE-844) reports of this occurring, but no solution yet. For now, tasks that experience this issue simply fail, though the task server should continue to run.
